openapi: 3.0.3
info:
  title: Youtube Video Sharing API
  version: 0.0.1
tags:
  - name: account
    description: Everything about your Pets
  - name: video
    description: Operations about user
paths:
  /account/registry:
    post:
      tags:
        - account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountRequestBody'
        required: true
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
        '400':
          description: Bad Request
  /account/login:
    post:
      tags:
        - account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountRequestBody'
        required: true
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: Bad Request
components:
  schemas:
    AccountRequestBody:
      type: object
      properties:
        email:
          type: string
          example: string@gmail.com
        password:
          type: string
    RegisterResponse:
      type: object
      properties:
        message:
          type: string
          example: Registry Successfully
    LoginResponse:
      type: object
      properties:
        message:
          type: string
          example: Login Successfully
        data:
          type: object
          properties:
            token:
              type: string
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header
