openapi: 3.0.3
info:
  title: Youtube Video Sharing API
  version: 0.0.1
paths:
  /api/account/info:
      post:
        security:
          - bearerAuth: []
        tags:
          - account
        responses:
          '200':
            description: Successful
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/AccountInfoResponse'
          '400':
            description: Bad Request
  /api/account/registry:
    post:
      tags:
        - account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountRequestBody'
        required: true
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
        '400':
          description: Bad Request
  /api/account/login:
    post:
      tags:
        - account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountRequestBody'
        required: true
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: Bad Request
  /api/video:
    get:
      tags:
        - video
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
        - in: query
          name: offset
          schema:
            type: integer
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetVideoResponse'
        '400':
          description: Bad Request
    post:
      security:
        - bearerAuth: []
      tags:
        - video
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  example: https://www.youtube.com/watch?v=videoId
                description:
                  type: string
        required: true
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostVideoResponse'
        '400':
          description: Bad Request
components:
  schemas:
    AccountEntity:
      type: object
      properties:
        email:
          type: string
    AccountInfoResponse:
      type: object
      properties:
        message:
          type: string
          example: Get Info Successfully
        data:
          $ref: '#/components/schemas/AccountEntity'
    AccountRequestBody:
      type: object
      properties:
        email:
          type: string
          example: string@gmail.com
        password:
          type: string
    RegisterResponse:
      type: object
      properties:
        message:
          type: string
          example: Registry Successfully
    LoginResponse:
      type: object
      properties:
        message:
          type: string
          example: Login Successfully
        data:
          type: object
          properties:
            token:
              type: string
    VideoEntity:
      type: object
      properties:
        id:
          type: string
        description:
          type: string
        email:
          type: string
    GetVideoResponse:
      type: object
      properties:
        message:
          type: string
          example: Get Video Successfully
        data:
          type: array
          items:
            $ref: '#/components/schemas/VideoEntity'
    PostVideoResponse:
      type: object
      properties:
        message:
          type: string
          example: Share Video Successfully
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
